export const REPORT_TEXT = {
  EN: {
    CONCLUSION: "Conclusion",
    METRICS: "Metrics",
    CONFIDENCE: "Confidence",
    ASSUMPTIONS: "Assumptions",
    LIMITATIONS: "Limitations",
    NEXT: "What to check next",
    DEFAULT_QUESTION: (topic) => `How is interest in "${topic}" changing?`,
    DEFAULT_NEXT:
      "Check related articles and other signals (search trends, surveys, competitor data) before investing.",
    COLUMNS: [
      "Language",
      "Article",
      "Views/month",
      "Trend",
      "Trend/yr",
      "YoY",
      "Confidence",
    ],
    TREND: {
      GROWING: "growing",
      DECLINING: "declining",
      NO_CLEAR_TREND: "no clear trend",
    },
    LEVEL: { HIGH: "high", MEDIUM: "medium", LOW: "low" },
    PERIOD: (start, end) => `Period: ${start} – ${end}, full calendar months.`,
    NORMALIZED:
      "Views are normalized per million views of the whole language edition.",
    RAW: "Raw monthly views, not normalized.",
    SPIKES_REMOVED:
      "One-day spikes (news, viral links) are replaced by the 29-day median.",
    SPIKES_KEPT: "One-day spikes are kept.",
    TREND_TEST:
      "Trend: seasonal Mann-Kendall test and Sen's slope, significant at p < 0.05.",
    TRAFFIC: "Traffic: human users, all devices.",
    CONFIDENCE_LINE: (lang, level, flags) =>
      `${lang}: ${level}${flags.length ? ` (${flags.join(", ")})` : ""}`,
    SOURCE: (date) =>
      `Source: Wikimedia Pageviews API and Wikidata. Data until ${date}. Generated by wikipedia-interest-analysis.`,
    LIMITATION: null,
  },
  UK: {
    CONCLUSION: "Висновок",
    METRICS: "Метрики",
    CONFIDENCE: "Рівень довіри",
    ASSUMPTIONS: "Припущення",
    LIMITATIONS: "Обмеження",
    NEXT: "Що перевірити далі",
    DEFAULT_QUESTION: (topic) => `Як змінюється інтерес до теми «${topic}»?`,
    DEFAULT_NEXT:
      "Перевірити пов'язані статті та інші сигнали (пошукові тренди, опитування, дані конкурентів) перед інвестуванням.",
    COLUMNS: [
      "Мова",
      "Стаття",
      "Перегл./міс.",
      "Тренд",
      "Тренд/рік",
      "Рік до року",
      "Довіра",
    ],
    TREND: {
      GROWING: "зростає",
      DECLINING: "спадає",
      NO_CLEAR_TREND: "немає чіткого тренду",
    },
    LEVEL: { HIGH: "висока", MEDIUM: "середня", LOW: "низька" },
    PERIOD: (start, end) =>
      `Період: ${start} – ${end}, повні календарні місяці.`,
    NORMALIZED:
      "Перегляди нормалізовано на мільйон переглядів усього мовного розділу.",
    RAW: "Сирі перегляди за місяць, без нормалізації.",
    SPIKES_REMOVED:
      "Одноденні сплески (новини, вірусні посилання) замінено медіаною за 29 днів.",
    SPIKES_KEPT: "Одноденні сплески не прибрано.",
    TREND_TEST:
      "Тренд: сезонний тест Манна-Кендалла і оцінка Сена, значущість p < 0,05.",
    TRAFFIC: "Трафік: люди, усі пристрої.",
    CONFIDENCE_LINE: (lang, level, flags) =>
      `${lang}: ${level}${flags.length ? ` (${flags.join(", ")})` : ""}`,
    SOURCE: (date) =>
      `Джерело: Wikimedia Pageviews API і Wikidata. Дані до ${date}. Згенеровано wikipedia-interest-analysis.`,
    LIMITATION: {
      GENERAL: [
        "Перегляди показують увагу до статті, а не готовність платити.",
        "Враховано лише основну статтю теми, без пов'язаних статей та інших сайтів.",
        "Трафік усієї Вікіпедії впав у 2025–2026 роках (відповіді ШІ, фільтрація ботів); нормалізація компенсує це лише частково.",
      ],
      VERY_LOW_VOLUME:
        "Дуже мало переглядів: випадкові коливання можуть переважати тренд.",
      LOW_VOLUME:
        "Мало переглядів: відсотки сильно коливаються на малих числах.",
      VERY_SHORT_HISTORY:
        "Даних менше ніж за рік: сезонність не відокремити від тренду.",
      SHORT_HISTORY:
        "Даних менше ніж за два роки: зростання рік до року недоступне, тест тренду слабкий.",
      LATE_START:
        "На початку періоду статті не було переглядів: її, ймовірно, створили чи перейменували, перегляди під старою назвою не враховано.",
      SPIKE_DRIVEN:
        "Тренд тримається на кількох днях-сплесках: без них напрям інший.",
      SPIKE_HEAVY:
        "Понад 20% переглядів припало на дні-сплески: інтерес подієвий, а не стабільний.",
      UNSTABLE_TREND:
        "Напрям тренду змінюється, якщо зсунути початок періоду на кілька місяців.",
      NOT_SIGNIFICANT:
        "Зміна статистично незначуща (p ≥ 0,05): це може бути шум.",
      RAW_NORMALIZED_DISAGREE:
        "Сирі й нормалізовані перегляди показують різні напрями: частина зміни — загальний трафік Вікіпедії.",
    },
  },
};
